# -*- coding: utf-8 -*-
"""TUGAS MATKUL PIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119dWl-mmYp91lkoOow1PANYl6CB2S0-f
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt
import json
from datetime import datetime

# =========================
# FILE PENYIMPANAN
# =========================
HASIL_FILE = "hasil.json"
SKOR_FILE = "skor_quiz.json"

def simpan_data(file, data):
    try:
        with open(file, "r") as f:
            data_lama = json.load(f)
    except:
        data_lama = []

    data_lama.append(data)

    with open(file, "w") as f:
        json.dump(data_lama, f, indent=4)

# =========================
# KONFIGURASI STREAMLIT
# =========================
st.set_page_config(
    page_title="Aplikasi Fisika Interaktif",
    page_icon="📘",
    layout="centered"
)

st.title("📘 Aplikasi Fisika Interaktif")
st.caption("Pembelajaran Fisika Dasar Berbasis Python + Streamlit")

menu = st.sidebar.selectbox(
    "📚 Pilih Menu",
    [
        "GLBB",
        "Hukum Newton",
        "Energi Mekanik",
        "Hukum Ohm",
        "Kalor",
        "Quiz Fisika",
        "Riwayat Data"
    ]
)

# =========================
# GLBB
# =========================
if menu == "GLBB":
    st.header("Gerak Lurus Berubah Beraturan (GLBB)")

    st.subheader("📐 Rumus")
    st.latex(r"s = v_0 t + \frac{1}{2} a t^2")
    st.latex(r"v = v_0 + a t")

    col1, col2 = st.columns(2)
    with col1:
        v0 = st.number_input("Kecepatan awal (m/s)", value=0.0)
        a = st.number_input("Percepatan (m/s²)", value=1.0)
    with col2:
        t_max = st.number_input("Waktu maksimum (s)", value=10)

    t = np.linspace(0, t_max, 100)
    s = v0 * t + 0.5 * a * t**2
    v = v0 + a * t

    st.subheader("📊 Hasil")
    st.write(f"📏 Jarak akhir: **{s[-1]:.2f} m**")
    st.write(f"🚀 Kecepatan akhir: **{v[-1]:.2f} m/s**")

    tab1, tab2 = st.tabs(["Grafik Posisi", "Grafik Kecepatan"])

    with tab1:
        fig1, ax1 = plt.subplots()
        ax1.plot(t, s)
        ax1.set_xlabel("Waktu (s)")
        ax1.set_ylabel("Posisi (m)")
        st.pyplot(fig1)

    with tab2:
        fig2, ax2 = plt.subplots()
        ax2.plot(t, v)
        ax2.set_xlabel("Waktu (s)")
        ax2.set_ylabel("Kecepatan (m/s)")
        st.pyplot(fig2)

    if st.button("💾 Simpan Hasil GLBB"):
        simpan_data(HASIL_FILE, {
            "waktu": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "materi": "GLBB",
            "jarak": s[-1],
            "kecepatan": v[-1]
        })
        st.success("Hasil berhasil disimpan")

# =========================
# HUKUM NEWTON
# =========================
elif menu == "Hukum Newton":
    st.header("Hukum Newton II")

    st.subheader("📐 Rumus")
    st.latex(r"F = m \times a")

    m = st.number_input("Massa (kg)", value=1.0)
    a = st.number_input("Percepatan (m/s²)", value=1.0)

    F = m * a
    st.success(f"Gaya = **{F:.2f} Newton**")

# =========================
# ENERGI MEKANIK
# =========================
elif menu == "Energi Mekanik":
    st.header("Energi Mekanik")

    st.subheader("📐 Rumus")
    st.latex(r"E_k = \frac{1}{2} m v^2")
    st.latex(r"E_p = m g h")
    st.latex(r"E_m = E_k + E_p")

    m = st.number_input("Massa (kg)", value=1.0)
    v = st.number_input("Kecepatan (m/s)", value=2.0)
    h = st.number_input("Ketinggian (m)", value=5.0)
    g = 9.8

    Ek = 0.5 * m * v**2
    Ep = m * g * h
    Em = Ek + Ep

    st.write(f"⚡ Energi Kinetik: **{Ek:.2f} J**")
    st.write(f"🏔️ Energi Potensial: **{Ep:.2f} J**")
    st.write(f"🔋 Energi Mekanik: **{Em:.2f} J**")

# =========================
# HUKUM OHM
# =========================
elif menu == "Hukum Ohm":
    st.header("Hukum Ohm")

    st.subheader("📐 Rumus")
    st.latex(r"V = I \times R")

    I = st.number_input("Arus (Ampere)", value=1.0)
    R = st.number_input("Hambatan (Ohm)", value=5.0)

    V = I * R
    st.success(f"Tegangan = **{V:.2f} Volt**")

# =========================
# KALOR
# =========================
elif menu == "Kalor":
    st.header("Perhitungan Kalor")

    st.subheader("📐 Rumus")
    st.latex(r"Q = m c \Delta T")

    m = st.number_input("Massa (kg)", value=1.0)
    c = st.number_input("Kalor jenis (J/kg°C)", value=4200.0)
    dT = st.number_input("Perubahan suhu (°C)", value=10.0)

    Q = m * c * dT
    st.success(f"Kalor = **{Q:.2f} Joule**")

# =========================
# QUIZ FISIKA
# =========================
elif menu == "Quiz Fisika":
    st.header("📝 Quiz Fisika")

    soal = {
        "pertanyaan": "Rumus yang benar untuk menghitung gaya adalah?",
        "opsi": ["F = m + a", "F = m × a", "F = m ÷ a"],
        "jawaban": 1
    }

    jawaban = st.radio(soal["pertanyaan"], soal["opsi"])

    if st.button("Cek Jawaban"):
        if soal["opsi"].index(jawaban) == soal["jawaban"]:
            st.success("Jawaban BENAR 🎉")
            skor = 100
        else:
            st.error("Jawaban SALAH ❌")
            skor = 0

        simpan_data(SKOR_FILE, {
            "waktu": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "skor": skor
        })

# =========================
# RIWAYAT
# =========================
elif menu == "Riwayat Data":
    st.header("📂 Riwayat Data")

    try:
        with open(HASIL_FILE) as f:
            st.subheader("Hasil Perhitungan")
            st.json(json.load(f))
    except:
        st.info("Belum ada data perhitungan")

    try:
        with open(SKOR_FILE) as f:
            st.subheader("Skor Quiz")
            st.json(json.load(f))
    except:
        st.info("Belum ada skor quiz")

st.markdown("---")
st.caption("Dibuat by Dirma")