# -*- coding: utf-8 -*-
"""TUGAS MATKUL PIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119dWl-mmYp91lkoOow1PANYl6CB2S0-f
"""

import streamlit as st
import random
from datetime import datetime

# =============================
# KONFIGURASI
# =============================
st.set_page_config("Fisika Interaktif", "📘", layout="centered")

ADMIN_USER = "Dirma"
ADMIN_PASS = "12345"

# =============================
# SESSION STATE
# =============================
if "login_admin" not in st.session_state:
    st.session_state.login_admin = False

if "hasil_quiz" not in st.session_state:
    st.session_state.hasil_quiz = []

# =============================
# BANK SOAL EDUKATIF
# =============================
quiz_bank = [
    {
        "materi": "GLBB",
        "tanya": "Rumus posisi pada GLBB adalah?",
        "opsi": ["s = vt", "s = v₀t + ½at²", "s = at", "s = ½vt²"],
        "jawaban": 1,
        "rumus": r"s = v_0 t + \frac{1}{2} a t^2",
        "penjelasan": "Karena terdapat percepatan tetap, posisi benda dihitung dengan rumus GLBB."
    },
    {
        "materi": "GLBB",
        "tanya": "Jika percepatan bernilai positif maka gerak benda?",
        "opsi": ["Diam", "GLB", "GLBB dipercepat", "GLBB diperlambat"],
        "jawaban": 2,
        "rumus": r"v = v_0 + at",
        "penjelasan": "Percepatan positif menyebabkan kecepatan bertambah."
    },
    {
        "materi": "Hukum Newton",
        "tanya": "Bunyi Hukum Newton II adalah?",
        "opsi": [
            "Gaya sebanding kecepatan",
            "Gaya sebanding massa dan percepatan",
            "Gaya selalu nol",
            "Gaya berbanding terbalik massa"
        ],
        "jawaban": 1,
        "rumus": r"F = m a",
        "penjelasan": "Gaya dipengaruhi oleh massa dan percepatan."
    },
    {
        "materi": "Energi",
        "tanya": "Rumus energi kinetik adalah?",
        "opsi": ["mgh", "½mv²", "mcΔT", "VIt"],
        "jawaban": 1,
        "rumus": r"E_k = \frac{1}{2} m v^2",
        "penjelasan": "Energi kinetik bergantung pada massa dan kecepatan benda."
    },
    {
        "materi": "Energi",
        "tanya": "Energi potensial gravitasi dipengaruhi oleh?",
        "opsi": ["Massa & kecepatan", "Massa & ketinggian", "Waktu", "Arus"],
        "jawaban": 1,
        "rumus": r"E_p = m g h",
        "penjelasan": "Semakin tinggi benda, semakin besar energi potensial."
    },
    {
        "materi": "Hukum Ohm",
        "tanya": "Rumus Hukum Ohm adalah?",
        "opsi": ["V = IR", "I = VR", "R = IV", "V = I + R"],
        "jawaban": 0,
        "rumus": r"V = I R",
        "penjelasan": "Tegangan berbanding lurus dengan arus."
    },
    {
        "materi": "Kalor",
        "tanya": "Rumus kalor adalah?",
        "opsi": ["mgh", "½mv²", "mcΔT", "VIt"],
        "jawaban": 2,
        "rumus": r"Q = m c \Delta T",
        "penjelasan": "Kalor dipengaruhi massa, kalor jenis, dan perubahan suhu."
    }
]

# =============================
# SIDEBAR MENU
# =============================
menu = st.sidebar.selectbox(
    "📚 Menu",
    [
        "GLBB",
        "Hukum Newton",
        "Energi",
        "Hukum Ohm",
        "Kalor",
        "Quiz Fisika",
        "Admin / Guru"
    ]
)

st.title("📘 Aplikasi Fisika Interaktif")
st.caption("Media pembelajaran fisika SMP & SMA")

# =============================
# MENU MATERI
# =============================
if menu == "GLBB":
    st.header("GLBB")
    st.latex(r"s = v_0 t + \frac{1}{2} a t^2")
    st.latex(r"v = v_0 + at")
    st.info("Gerak lurus dengan percepatan tetap.")

elif menu == "Hukum Newton":
    st.header("Hukum Newton II")
    st.latex(r"F = ma")
    st.info("Gaya sebanding dengan percepatan.")

elif menu == "Energi":
    st.header("Energi")
    st.latex(r"E_k = \frac{1}{2}mv^2")
    st.latex(r"E_p = mgh")
    st.info("Energi kinetik dan potensial.")

elif menu == "Hukum Ohm":
    st.header("Hukum Ohm")
    st.latex(r"V = IR")
    st.info("Hubungan tegangan, arus, hambatan.")

elif menu == "Kalor":
    st.header("Kalor")
    st.latex(r"Q = mc\Delta T")
    st.info("Kalor adalah energi panas.")

# =============================
# QUIZ
# =============================
elif menu == "Quiz Fisika":
    st.header("📝 Quiz Fisika")

    nama = st.text_input("Nama Siswa")
    mode = st.radio("Mode", ["Latihan", "Ujian"])
    materi = st.selectbox(
        "Materi",
        ["Semua", "GLBB", "Hukum Newton", "Energi", "Hukum Ohm", "Kalor"]
    )

    soal_list = quiz_bank if materi == "Semua" else [q for q in quiz_bank if q["materi"] == materi]
    random.shuffle(soal_list)

    if "index" not in st.session_state:
        st.session_state.index = 0
        st.session_state.skor = 0
        st.session_state.start = datetime.now()

    if mode == "Ujian":
        batas = 60
        jalan = (datetime.now() - st.session_state.start).seconds
        sisa = batas - jalan
        st.warning(f"⏱️ Sisa waktu: {sisa} detik")
        if sisa <= 0:
            st.error("Waktu habis!")
            st.stop()

    if st.session_state.index < len(soal_list):
        soal = soal_list[st.session_state.index]
        jawab = st.radio(soal["tanya"], soal["opsi"], key=st.session_state.index)

        if st.button("Jawab"):
            if soal["opsi"].index(jawab) == soal["jawaban"]:
                st.success("Benar ✅")
                st.session_state.skor += 10
            else:
                st.error("Salah ❌")

            if mode == "Latihan":
                st.latex(soal["rumus"])
                st.info(soal["penjelasan"])

            st.session_state.index += 1
            st.experimental_rerun()
    else:
        st.success(f"Skor akhir: {st.session_state.skor}")
        st.session_state.hasil_quiz.append({
            "Nama": nama,
            "Skor": st.session_state.skor,
            "Mode": mode,
            "Waktu": datetime.now().strftime("%d-%m-%Y %H:%M")
        })

# =============================
# ADMIN
# =============================
elif menu == "Admin / Guru":
    st.header("👨‍🏫 Menu Admin")

    if not st.session_state.login_admin:
        u = st.text_input("Username")
        p = st.text_input("Password", type="password")
        if st.button("Login"):
            if u == ADMIN_USER and p == ADMIN_PASS:
                st.session_state.login_admin = True
                st.experimental_rerun()
            else:
                st.error("Login gagal")
    else:
        st.success("Login admin berhasil")

        if st.session_state.hasil_quiz:
            st.subheader("📊 Hasil Quiz Siswa")
            st.table(st.session_state.hasil_quiz)
        else:
            st.info("Belum ada data")

        if st.button("Logout"):
            st.session_state.login_admin = False
            st.experimental_rerun()

st.markdown("---")
st.caption("by Dirma")