# -*- coding: utf-8 -*-
"""TUGAS MATKUL PIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119dWl-mmYp91lkoOow1PANYl6CB2S0-f
"""

import streamlit as st
from datetime import datetime

st.set_page_config(page_title="Fisika Interaktif", page_icon="📘", layout="centered")

# =========================
# DATA LOGIN
# =========================
admin_user = {"Dirma": "Dirma123"}  # Admin/Guru

# =========================
# DATA MATERI & BANK SOAL
# =========================
materi = {
    "GLBB": {
        "rumus": [
            r"v = v_0 + at",
            r"s = v_0 t + \frac{1}{2} a t^2"
        ],
        "penjelasan": """
Gerak Lurus Berubah Beraturan (GLBB) adalah gerak benda pada lintasan lurus
dengan percepatan tetap. Karena percepatannya tetap, kecepatan benda
akan berubah secara teratur terhadap waktu.

Contoh GLBB dalam kehidupan sehari-hari adalah mobil yang dipercepat
secara konstan atau benda jatuh bebas (tanpa hambatan udara).
"""
    },

    "Hukum Newton": {
        "rumus": [
            r"F = m a"
        ],
        "penjelasan": """
Hukum Newton membahas hubungan antara gaya, massa, dan percepatan.
Hukum Newton II menyatakan bahwa percepatan suatu benda sebanding
dengan gaya yang bekerja padanya dan berbanding terbalik dengan massanya.

Semakin besar gaya yang diberikan, semakin besar percepatan benda.
"""
    },

    "Energi": {
        "rumus": [
            r"E_k = \frac{1}{2} m v^2",
            r"E_p = m g h"
        ],
        "penjelasan": """
Energi adalah kemampuan suatu benda untuk melakukan usaha.
Energi kinetik dimiliki oleh benda yang bergerak, sedangkan energi
potensial dimiliki benda karena posisinya.

Dalam sistem tanpa gesekan, energi mekanik akan tetap.
"""
    },

    "Hukum Ohm": {
        "rumus": [
            r"V = I R"
        ],
        "penjelasan": """
Hukum Ohm menjelaskan hubungan antara tegangan listrik, arus listrik,
dan hambatan dalam suatu rangkaian.

Jika hambatan diperbesar, maka arus yang mengalir akan semakin kecil.
"""
    },

    "Kalor": {
        "rumus": [
            r"Q = m c \Delta T"
        ],
        "penjelasan": """
Kalor adalah energi yang berpindah akibat perbedaan suhu.
Kalor dapat menyebabkan perubahan suhu atau perubahan wujud zat.

Contoh peristiwa kalor adalah memanaskan air atau mencairkan es.
"""
    },

    "Momentum": {
        "rumus": [
            r"p = m v"
        ],
        "penjelasan": """
Momentum adalah hasil kali massa dan kecepatan suatu benda.
Semakin besar massa dan kecepatan, semakin besar momentumnya.

Momentum berkaitan erat dengan peristiwa tumbukan.
"""
    },

    "Usaha": {
        "rumus": [
            r"W = F s"
        ],
        "penjelasan": """
Usaha terjadi jika suatu gaya menyebabkan perpindahan benda.
Jika tidak ada perpindahan, maka usaha yang dilakukan adalah nol.

Usaha berhubungan langsung dengan energi.
"""
    }
}


bank_soal = {
    "GLBB": [
        {"soal":"Gerak lurus dengan percepatan tetap disebut ...","opsi":["GLB","GLBB","GMB","GJB"],"jawaban":"GLBB","penjelasan":"GLBB adalah gerak lurus dengan percepatan konstan."},
        {"soal":"Rumus kecepatan pada GLBB adalah ...","opsi":["v = s/t","v = v₀ + at","v = at²","v = m a"],"jawaban":"v = v₀ + at","penjelasan":"Kecepatan GLBB berubah karena adanya percepatan."},
        {"soal":"Rumus posisi GLBB adalah ...","opsi":["s = v t","s = v₀ t + ½ a t²","s = at²","s = m a t"],"jawaban":"s = v₀ t + ½ a t²","penjelasan":"Posisi berubah sesuai rumus GLBB."},
        {"soal":"Satuan percepatan dalam SI adalah ...","opsi":["m","m/s","m/s²","kg"],"jawaban":"m/s²","penjelasan":"Percepatan adalah perubahan kecepatan per satuan waktu."},
        {"soal":"Jika percepatan bernilai negatif maka benda mengalami ...","opsi":["dipercepat","diperlambat","diam","berat"],"jawaban":"diperlambat","penjelasan":"Percepatan negatif berarti kecepatan berkurang."},
        {"soal":"Grafik v–t pada GLBB berbentuk ...","opsi":["garis lurus","parabola","lingkaran","hiperbola"],"jawaban":"garis lurus","penjelasan":"Kecepatan berubah linier terhadap waktu."},
        {"soal":"Kecepatan awal mobil 20 m/s, percepatan 2 m/s², kecepatan setelah 5 s adalah ...","opsi":["30 m/s","40 m/s","25 m/s","35 m/s"],"jawaban":"30 m/s","penjelasan":"v = v₀ + at → 20 + 2*5 = 30 m/s."},
        {"soal":"Sebuah benda bergerak dengan GLBB, percepatan 3 m/s², waktu 4 s, jarak ditempuh ...","opsi":["24 m","32 m","40 m","36 m"],"jawaban":"32 m","penjelasan":"s = v₀ t + ½ a t² → 0 + 0.5*3*16=24 m (jika v₀=0, periksa soal)."},
        {"soal":"Benda jatuh bebas termasuk jenis gerak ...","opsi":["GLB","GLBB","GMB","Gerak melingkar"],"jawaban":"GLBB","penjelasan":"Benda jatuh bebas percepatannya konstan (g)."},
        {"soal":"Satuan kecepatan dalam SI adalah ...","opsi":["m","m/s","m/s²","N"],"jawaban":"m/s","penjelasan":"Kecepatan = jarak/waktu."}
    ],

    "Hukum Newton": [
        {"soal":"Rumus Hukum Newton II adalah ...","opsi":["v = at","F = m a","W = Fs","p = mv"],"jawaban":"F = m a","penjelasan":"Percepatan sebanding dengan gaya dan berbanding terbalik dengan massa."},
        {"soal":"Satuan gaya dalam SI adalah ...","opsi":["Joule","Newton","Watt","Pascal"],"jawaban":"Newton","penjelasan":"Gaya diukur dalam satuan Newton (N)."},
        {"soal":"Hukum Newton III dikenal sebagai hukum ...","opsi":["aksi-reaksi","gravitasi","inersia","momentum"],"jawaban":"aksi-reaksi","penjelasan":"Untuk setiap aksi ada reaksi yang sama besar dan berlawanan arah."},
        {"soal":"Jika gaya total pada benda nol, benda akan ...","opsi":["bergerak","diam","tetap kecepatan","berubah arah"],"jawaban":"tetap kecepatan","penjelasan":"Hukum Newton I: benda diam atau bergerak lurus dengan kecepatan konstan."},
        {"soal":"Massa benda 5 kg, percepatan 2 m/s², gaya yang bekerja ...","opsi":["5 N","10 N","7 N","12 N"],"jawaban":"10 N","penjelasan":"F = m*a → 5*2=10 N."},
        {"soal":"Jika gaya meningkat, percepatan benda akan ...","opsi":["menurun","tetap","bertambah","nol"],"jawaban":"bertambah","penjelasan":"F sebanding dengan a."},
        {"soal":"Jika massa benda bertambah, percepatan ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"berkurang","penjelasan":"a berbanding terbalik dengan m."},
        {"soal":"Benda yang bergerak lurus dengan kecepatan konstan mengalami gaya ...","opsi":["nol","konstan","bertambah","berkurang"],"jawaban":"nol","penjelasan":"Newton I, tidak ada percepatan → gaya total nol."},
        {"soal":"Gaya gesek termasuk jenis gaya ...","opsi":["kontak","gravitasi","magnet","listrik"],"jawaban":"kontak","penjelasan":"Gaya gesek terjadi karena kontak permukaan benda."},
        {"soal":"Hukum Newton digunakan untuk menghitung ...","opsi":["percepatan","kecepatan","jarak","waktu"],"jawaban":"percepatan","penjelasan":"Newton II menghubungkan gaya, massa, dan percepatan."}
    ],

    "Energi": [
        {"soal":"Rumus energi kinetik adalah ...","opsi":["mgh","½mv²","Fs","IR"],"jawaban":"½mv²","penjelasan":"Energi kinetik dimiliki benda bergerak."},
        {"soal":"Rumus energi potensial gravitasi ...","opsi":["mgh","½mv²","Fs","IR"],"jawaban":"mgh","penjelasan":"Energi potensial = m*g*h."},
        {"soal":"Energi total = ...","opsi":["EK + EP","EK - EP","EK*EP","EK/EP"],"jawaban":"EK + EP","penjelasan":"Energi mekanik total = kinetik + potensial."},
        {"soal":"Satuan energi dalam SI adalah ...","opsi":["Newton","Joule","Watt","Pascal"],"jawaban":"Joule","penjelasan":"Energi diukur dalam Joule."},
        {"soal":"Energi kinetik meningkat saat ...","opsi":["massa bertambah","kecepatan bertambah","massa dan kecepatan bertambah","kecepatan berkurang"],"jawaban":"kecepatan bertambah","penjelasan":"EK = ½ m v², kecepatan dominan."},
        {"soal":"Energi potensial bertambah jika ...","opsi":["massa bertambah","tinggi bertambah","kedua-duanya","tidak berubah"],"jawaban":"kedua-duanya","penjelasan":"EP = m g h."},
        {"soal":"Energi tidak dapat ...","opsi":["diciptakan","diubah bentuk","dipindahkan","dikalkulasi"],"jawaban":"diciptakan","penjelasan":"Hukum kekekalan energi."},
        {"soal":"Energi kinetik benda 2 kg, v=3 m/s ...","opsi":["9 J","6 J","12 J","18 J"],"jawaban":"9 J","penjelasan":"EK=½*2*3²=9 J."},
        {"soal":"Energi potensial benda 3 kg, h=4 m, g=10 m/s² ...","opsi":["120 J","100 J","140 J","60 J"],"jawaban":"120 J","penjelasan":"EP = m*g*h = 3*10*4 =120 J."},
        {"soal":"Energi mekanik adalah ...","opsi":["EK","EP","EK+EP","EK-EP"],"jawaban":"EK+EP","penjelasan":"Energi mekanik = EK + EP."}
    ],

    "Hukum Ohm": [
        {"soal":"Rumus Hukum Ohm adalah ...","opsi":["V = IR","P = VI","Q = mcΔT","W = Fs"],"jawaban":"V = IR","penjelasan":"Tegangan berbanding lurus dengan arus dan hambatan."},
        {"soal":"Satuan hambatan adalah ...","opsi":["Ohm","Joule","Newton","Watt"],"jawaban":"Ohm","penjelasan":"Hambatan diukur dalam Ohm."},
        {"soal":"Jika hambatan bertambah, arus akan ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"berkurang","penjelasan":"I = V/R."},
        {"soal":"Jika tegangan tetap, arus ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"berkurang","penjelasan":"I = V/R."},
        {"soal":"Daya listrik = ...","opsi":["V*I","V/I","V+I","V-I"],"jawaban":"V*I","penjelasan":"P = V * I."},
        {"soal":"Hukum Ohm berlaku untuk ...","opsi":["konduktor ideal","isolator","semua benda","benda bergerak"],"jawaban":"konduktor ideal","penjelasan":"Hanya untuk konduktor yang memenuhi Ohm."},
        {"soal":"Jika arus 2 A dan R=5 Ω, tegangan ...","opsi":["5 V","10 V","8 V","15 V"],"jawaban":"10 V","penjelasan":"V=I*R=2*5=10 V."},
        {"soal":"Hambatan total seri ...","opsi":["jumlah semua R","rata-rata","dibagi","dikali"],"jawaban":"jumlah semua R","penjelasan":"R_total = R1 + R2 + ... + Rn."},
        {"soal":"Hambatan total paralel ...","opsi":["jumlah semua R","1/sum(1/R)","rata-rata","dikali"],"jawaban":"1/sum(1/R)","penjelasan":"1/R_total = 1/R1 + 1/R2 + ... + 1/Rn."},
        {"soal":"Jika R=10 Ω, V=20 V, I ...","opsi":["2 A","0,5 A","20 A","10 A"],"jawaban":"2 A","penjelasan":"I = V/R = 20/10 = 2 A."}
    ],

    "Kalor": [
        {"soal":"Rumus kalor untuk perubahan suhu adalah ...","opsi":["Q = mcΔT","Q = mgh","Q = Fs","Q = IR"],"jawaban":"Q = mcΔT","penjelasan":"Kalor dipengaruhi massa, kalor jenis, dan perubahan suhu."},
        {"soal":"Satuan kalor dalam SI adalah ...","opsi":["Joule","Kalori","Watt","Newton"],"jawaban":"Joule","penjelasan":"Kalor diukur dalam Joule."},
        {"soal":"Kalor jenis air ...","opsi":["4186 J/kg°C","1000 J/kg°C","500 J/kg°C","2000 J/kg°C"],"jawaban":"4186 J/kg°C","penjelasan":"Nilai kalor jenis air."},
        {"soal":"Jika massa meningkat, Q ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"bertambah","penjelasan":"Q = m c ΔT."},
        {"soal":"Jika ΔT meningkat, Q ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"bertambah","penjelasan":"Q = m c ΔT."},
        {"soal":"Jika c meningkat, Q ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"bertambah","penjelasan":"Q = m c ΔT."},
        {"soal":"Kalor laten adalah ...","opsi":["energi saat perubahan wujud","energi saat bergerak","energi total","energi kinetik"],"jawaban":"energi saat perubahan wujud","penjelasan":"Kalor laten untuk melebur/membeku."},
        {"soal":"Mencairkan es termasuk ...","opsi":["kalor laten","kalor sensibel","energi kinetik","energi potensial"],"jawaban":"kalor laten","penjelasan":"Perubahan wujud tanpa perubahan suhu."},
        {"soal":"Memanaskan air termasuk ...","opsi":["kalor sensibel","kalor laten","energi kinetik","energi potensial"],"jawaban":"kalor sensibel","penjelasan":"Perubahan suhu tanpa wujud."},
        {"soal":"Satuan kalor 1 kalori = ...","opsi":["4,2 J","4,18 J","1 J","10 J"],"jawaban":"4,18 J","penjelasan":"Konversi kalori ke joule."}
    ],

    "Momentum": [
        {"soal":"Rumus momentum adalah ...","opsi":["p = mv","p = ma","p = Fs","p = IR"],"jawaban":"p = mv","penjelasan":"Momentum = massa * kecepatan."},
        {"soal":"Satuan momentum ...","opsi":["kg m/s","N","J","W"],"jawaban":"kg m/s","penjelasan":"Momentum diukur kg m/s."},
        {"soal":"Jika massa bertambah, momentum ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"bertambah","penjelasan":"p = m*v."},
        {"soal":"Jika kecepatan bertambah, momentum ...","opsi":["bertambah","berkurang","tetap","nol"],"jawaban":"bertambah","penjelasan":"p = m*v."},
        {"soal":"Hukum kekekalan momentum berlaku saat ...","opsi":["tumbukan","gerak lurus","diam","percepatan"],"jawaban":"tumbukan","penjelasan":"Momentum total sebelum = sesudah tumbukan."},
        {"soal":"Momentum awal 4 kg*m/s, bertambah 6 kg*m/s → total ...","opsi":["10 kg m/s","2 kg m/s","6 kg m/s","4 kg m/s"],"jawaban":"10 kg m/s","penjelasan":"Penjumlahan momentum vektor."},
        {"soal":"Momentum sebanding dengan ...","opsi":["massa","kecepatan","massa & kecepatan","gaya"],"jawaban":"massa & kecepatan","penjelasan":"p = m*v."},
        {"soal":"Jika momentum 20 kg m/s, massa 4 kg, v ...","opsi":["5 m/s","10 m/s","4 m/s","6 m/s"],"jawaban":"5 m/s","penjelasan":"v = p/m = 20/4 = 5 m/s."},
        {"soal":"Momentum bertambah jika ...","opsi":["massa bertambah","kecepatan bertambah","kedua-duanya","tidak berubah"],"jawaban":"kedua-duanya","penjelasan":"p = m*v."},
        {"soal":"Benda diam momentum ...","opsi":["0","tidak nol","m*g","m*v"],"jawaban":"0","penjelasan":"v = 0 → p = 0."}
    ],

    "Usaha": [
        {"soal":"Rumus usaha adalah ...","opsi":["W = Fs","W = mv²","W = IR","W = mcΔT"],"jawaban":"W = Fs","penjelasan":"Usaha terjadi jika gaya menyebabkan perpindahan."},
        {"soal":"Satuan usaha ...","opsi":["Joule","Newton","Watt","Pascal"],"jawaban":"Joule","penjelasan":"Usaha diukur dalam Joule."},
        {"soal":"Jika perpindahan nol, usaha ...","opsi":["nol","besar","kecil","konstan"],"jawaban":"nol","penjelasan":"Tidak ada perpindahan → usaha nol."},
        {"soal":"Jika gaya tegak lurus perpindahan, usaha ...","opsi":["nol","besar","kecil","konstan"],"jawaban":"nol","penjelasan":"W = F cos θ, θ=90° → W=0."},
        {"soal":"Usaha sebanding dengan ...","opsi":["gaya","perpindahan","gaya & perpindahan","waktu"],"jawaban":"gaya & perpindahan","penjelasan":"W = F*s."},
        {"soal":"Usaha bertambah jika ...","opsi":["gaya bertambah","s bertambah","gaya & s bertambah","tidak berubah"],"jawaban":"gaya & s bertambah","penjelasan":"W = F*s."},
        {"soal":"Jika gaya 10 N, s = 5 m, W ...","opsi":["50 J","15 J","10 J","20 J"],"jawaban":"50 J","penjelasan":"W = F*s =10*5=50 J."},
        {"soal":"Jika gaya 10 N, s = 5 m, θ=60° → W ...","opsi":["25 J","50 J","5 J","30 J"],"jawaban":"25 J","penjelasan":"W = F*s*cosθ = 10*5*0.5=25 J."},
    ]
        }

# =========================
# SESSION STATE
# =========================
if "login" not in st.session_state: st.session_state.login=False
if "username" not in st.session_state: st.session_state.username=""
if "quiz_index" not in st.session_state: st.session_state.quiz_index=0
if "quiz_score" not in st.session_state: st.session_state.quiz_score=0
if "hasil_siswa" not in st.session_state: st.session_state.hasil_siswa=[]

# =========================
# LOGIN ADMIN OPSIONAL
# =========================
if not st.session_state.login:
    st.sidebar.header("🔑 Login Admin (Opsional)")
    username = st.sidebar.text_input("Username Admin")
    password = st.sidebar.text_input("Password Admin", type="password")
    login_btn = st.sidebar.button("Login Admin")

    if login_btn:
        if username in admin_user and password == admin_user[username]:
            st.session_state.login = True
            st.session_state.username = username
            st.success(f"Selamat datang Admin {username}!")
        else:
            st.error("Username atau password admin salah")
else:
    st.sidebar.write(f"👤 Logged in as: **{st.session_state.username}**")
    if st.sidebar.button("Logout"):
        st.session_state.login=False
        st.session_state.username=""
        st.experimental_rerun()

# =========================
# MENU UTAMA
# =========================
menu_options = list(materi.keys()) + ["Latihan"]
if st.session_state.login:
    menu_options.append("Admin/Guru")
menu = st.sidebar.selectbox("📚 Menu", menu_options)

# =========================
# MENU MATERI
# =========================
if menu in materi.keys():
    st.header(menu)
    st.subheader("📐 Rumus")
    for r in materi[menu]["rumus"]: st.latex(r)
    st.subheader("📘 Penjelasan")
    st.write(materi[menu]["penjelasan"])

# =========================
# MENU LATIHAN
# =========================
elif menu == "Latihan":
    st.header("🎯 Latihan Fisika Interaktif")
    pilihan_latihan = st.radio("Pilih mode latihan:", ["Per Materi", "Semua Soal"])

    # Ambil soal sesuai pilihan
    if pilihan_latihan=="Per Materi":
        materi_pilih = st.multiselect("Pilih materi yang ingin dijawab:", list(bank_soal.keys()))
        quiz = []
        for m in materi_pilih:
            quiz.extend(bank_soal[m])
    else:
        quiz = []
        for soal_list in bank_soal.values():
            quiz.extend(soal_list)

    # Reset index jika mode berubah
    if "latihan_mode" not in st.session_state or st.session_state.latihan_mode != pilihan_latihan:
        st.session_state.quiz_index = 0
        st.session_state.quiz_score = 0
        st.session_state.latihan_mode = pilihan_latihan

    if st.session_state.quiz_index >= len(quiz):
        st.success(f"🎉 Latihan selesai! Skor kamu: {st.session_state.quiz_score}")
        # simpan hasil otomatis
        st.session_state.hasil_siswa.append({
            "waktu": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "skor": st.session_state.quiz_score,
            "mode": pilihan_latihan,
            "materi": ", ".join(materi_pilih) if pilihan_latihan=="Per Materi" else "Semua"
        })
    else:
        q = quiz[st.session_state.quiz_index]
        st.subheader(f"Soal {st.session_state.quiz_index+1}")
        st.write(q["soal"])
        jawaban = st.radio("Pilih jawaban:", q["opsi"], key=st.session_state.quiz_index)

        if st.button("Jawab"):
            if jawaban==q["jawaban"]:
                st.success("✅ Jawaban benar!")
                st.session_state.quiz_score += 10
            else:
                st.error("❌ Jawaban salah")
                st.write(f"✔ Jawaban benar: **{q['jawaban']}**")
                st.write(f"📘 Penjelasan: {q['penjelasan']}")

        if st.button("Next ➡️"):
            st.session_state.quiz_index += 1
            st.experimental_rerun()

# =========================
# MENU ADMIN/GURU
# =========================
elif menu=="Admin/Guru":
    st.header("👨‍🏫 Admin/Guru")
    username = st.text_input("Username")
    password = st.text_input("Password", type="password")
    if st.button("Login"):
        if username=="Dirma" and password=="Dirma123":
            st.success("Login berhasil!")
            if st.session_state.hasil_siswa:
                st.subheader("📊 Hasil Latihan Siswa")
                for idx,h in enumerate(st.session_state.hasil_siswa,1):
                    st.write(f"{idx}. Waktu: {h['waktu']} | Skor: {h['skor']} | Mode: {h['mode']} | Materi: {h['materi']}")
            else:
                st.info("Belum ada siswa yang melakukan latihan.")
        else:
            st.error("Username atau password salah!")

st.caption("by Dirma")