# -*- coding: utf-8 -*-
"""TUGAS MATKUL PIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119dWl-mmYp91lkoOow1PANYl6CB2S0-f
"""

import streamlit as st
import numpy as np
import matplotlib.pyplot as plt

st.set_page_config(
    page_title="Aplikasi Fisika Dasar",
    page_icon="📘",
    layout="centered"
)

st.title("📘 Aplikasi Fisika Dasar")
st.write("Aplikasi ini berisi perhitungan dan simulasi rumus fisika dasar.")

menu = st.sidebar.selectbox(
    "Pilih Menu",
    [
        "Gerak Lurus (GLBB)",
        "Hukum Newton",
        "Energi Mekanik",
        "Hukum Ohm",
        "Kalor"
    ]
)


# GLBB

if menu == "Gerak Lurus (GLBB)":
    st.header("Gerak Lurus Berubah Beraturan (GLBB)")

    v0 = st.number_input("Kecepatan awal (m/s)", value=0.0)
    a = st.number_input("Percepatan (m/s²)", value=1.0)
    t_max = st.number_input("Waktu maksimum (s)", value=10)

    t = np.linspace(0, t_max, 100)
    s = v0 * t + 0.5 * a * t**2
    v = v0 + a * t

    st.subheader("Hasil Perhitungan")
    st.write(f"Jarak akhir: **{s[-1]:.2f} m**")
    st.write(f"Kecepatan akhir: **{v[-1]:.2f} m/s**")

    fig, ax = plt.subplots()
    ax.plot(t, s)
    ax.set_xlabel("Waktu (s)")
    ax.set_ylabel("Posisi (m)")
    ax.set_title("Grafik Posisi terhadap Waktu")
    st.pyplot(fig)

# Hukum Newton

elif menu == "Hukum Newton":
    st.header("Hukum Newton II")

    m = st.number_input("Massa (kg)", value=1.0)
    a = st.number_input("Percepatan (m/s²)", value=1.0)

    F = m * a
    st.subheader("Hasil")
    st.write(f"Gaya: **{F:.2f} Newton**")


# Energi Mekanik

elif menu == "Energi Mekanik":
    st.header("Energi Kinetik & Potensial")

    m = st.number_input("Massa (kg)", value=1.0)
    v = st.number_input("Kecepatan (m/s)", value=2.0)
    h = st.number_input("Ketinggian (m)", value=5.0)
    g = 9.8

    Ek = 0.5 * m * v**2
    Ep = m * g * h
    Em = Ek + Ep

    st.subheader("Hasil")
    st.write(f"Energi Kinetik: **{Ek:.2f} J**")
    st.write(f"Energi Potensial: **{Ep:.2f} J**")
    st.write(f"Energi Mekanik Total: **{Em:.2f} J**")


# Hukum Ohm

elif menu == "Hukum Ohm":
    st.header("Hukum Ohm")

    I = st.number_input("Arus (Ampere)", value=1.0)
    R = st.number_input("Hambatan (Ohm)", value=5.0)

    V = I * R
    st.subheader("Hasil")
    st.write(f"Tegangan: **{V:.2f} Volt**")


# Kalor

elif menu == "Kalor":
    st.header("Perhitungan Kalor")

    m = st.number_input("Massa (kg)", value=1.0)
    c = st.number_input("Kalor Jenis (J/kg°C)", value=4200.0)
    dT = st.number_input("Perubahan Suhu (°C)", value=10.0)

    Q = m * c * dT
    st.subheader("Hasil")
    st.write(f"Kalor: **{Q:.2f} Joule**")

st.markdown("---")
st.caption("Dibuat menggunakan Python & Streamlit")