# -*- coding: utf-8 -*-
"""TUGAS MATKUL PIK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/119dWl-mmYp91lkoOow1PANYl6CB2S0-f
"""

import streamlit as st
from datetime import datetime

# =========================
# KONFIGURASI
# =========================
st.set_page_config(
    page_title="Fisika Interaktif",
    page_icon="📘",
    layout="centered"
)

# =========================
# DATA LOGIN
# =========================
users = {
    "admin": "Dirma123",
    "user": "Dirma123"
}

# =========================
# DATA MATERI
# =========================
materi = {
    "GLBB": {
        "rumus": [
            r"v = v_0 + at",
            r"s = v_0 t + \frac{1}{2} a t^2"
        ],
        "penjelasan": """
Gerak Lurus Berubah Beraturan (GLBB) adalah gerak benda pada lintasan lurus
dengan percepatan tetap. Kecepatan benda akan berubah secara teratur terhadap waktu.
"""
    },
    "Hukum Newton": {
        "rumus": [
            r"F = m a"
        ],
        "penjelasan": """
Hukum Newton II menyatakan bahwa percepatan suatu benda sebanding
dengan gaya yang bekerja padanya dan berbanding terbalik dengan massanya.
"""
    },
    "Energi": {
        "rumus": [
            r"E_k = \frac{1}{2} m v^2",
            r"E_p = m g h"
        ],
        "penjelasan": """
Energi kinetik dimiliki benda yang bergerak, sedangkan energi potensial
dimiliki benda karena posisinya. Energi mekanik tetap jika tanpa gesekan.
"""
    },
    "Hukum Ohm": {
        "rumus": [r"V = I R"],
        "penjelasan": "Hukum Ohm menjelaskan hubungan antara tegangan, arus, dan hambatan."
    },
    "Kalor": {
        "rumus": [r"Q = m c \Delta T"],
        "penjelasan": "Kalor adalah energi yang berpindah akibat perbedaan suhu."
    },
    "Momentum": {
        "rumus": [r"p = m v"],
        "penjelasan": "Momentum adalah hasil kali massa dan kecepatan suatu benda."
    },
    "Usaha": {
        "rumus": [r"W = F s"],
        "penjelasan": "Usaha terjadi jika suatu gaya menyebabkan perpindahan benda."
    }
}

# =========================
# BANK SOAL QUIZ
# =========================
bank_soal = {
    "GLBB": [
        {"soal": "Gerak lurus dengan percepatan tetap disebut ...",
         "opsi": ["GLB", "GLBB", "GMB", "GJB"],
         "jawaban": "GLBB",
         "penjelasan": "GLBB adalah gerak lurus dengan percepatan konstan."},
        {"soal": "Rumus kecepatan pada GLBB adalah ...",
         "opsi": ["v = s/t", "v = v₀ + at", "v = at²", "v = m a"],
         "jawaban": "v = v₀ + at",
         "penjelasan": "Kecepatan GLBB berubah karena adanya percepatan."},
        {"soal": "Satuan percepatan dalam SI adalah ...",
         "opsi": ["m", "m/s", "m/s²", "kg"],
         "jawaban": "m/s²",
         "penjelasan": "Percepatan adalah perubahan kecepatan per satuan waktu."},
        {"soal": "Jika percepatan bernilai negatif maka benda mengalami ...",
         "opsi": ["dipercepat", "diperlambat", "diam", "berat"],
         "jawaban": "diperlambat",
         "penjelasan": "Percepatan negatif berarti kecepatan berkurang."},
        {"soal": "Grafik v–t pada GLBB berbentuk ...",
         "opsi": ["garis lurus", "parabola", "lingkaran", "hiperbola"],
         "jawaban": "garis lurus",
         "penjelasan": "Kecepatan berubah linier terhadap waktu."}
    ],
    "Hukum Newton": [
        {"soal": "Rumus Hukum Newton II adalah ...",
         "opsi": ["v = at", "F = m a", "W = Fs", "p = mv"],
         "jawaban": "F = m a",
         "penjelasan": "Percepatan sebanding dengan gaya dan berbanding terbalik dengan massa."},
        {"soal": "Satuan gaya dalam SI adalah ...",
         "opsi": ["Joule", "Newton", "Watt", "Pascal"],
         "jawaban": "Newton",
         "penjelasan": "Gaya diukur dalam satuan Newton (N)."}
    ],
    "Energi": [
        {"soal": "Rumus energi kinetik adalah ...",
         "opsi": ["mgh", "½mv²", "Fs", "IR"],
         "jawaban": "½mv²",
         "penjelasan": "Energi kinetik dimiliki benda yang bergerak."}
    ],
    "Hukum Ohm": [
        {"soal": "Rumus Hukum Ohm adalah ...",
         "opsi": ["V = IR", "P = VI", "Q = mcΔT", "W = Fs"],
         "jawaban": "V = IR",
         "penjelasan": "Tegangan berbanding lurus dengan arus dan hambatan."}
    ],
    "Kalor": [
        {"soal": "Rumus kalor untuk perubahan suhu adalah ...",
         "opsi": ["Q = mcΔT", "Q = mgh", "Q = Fs", "Q = IR"],
         "jawaban": "Q = mcΔT",
         "penjelasan": "Kalor dipengaruhi massa, kalor jenis, dan perubahan suhu."}
    ],
    "Momentum": [
        {"soal": "Rumus momentum adalah ...",
         "opsi": ["p = mv", "p = ma", "p = Fs", "p = IR"],
         "jawaban": "p = mv",
         "penjelasan": "Momentum adalah hasil kali massa dan kecepatan."}
    ],
    "Usaha": [
        {"soal": "Rumus usaha adalah ...",
         "opsi": ["W = Fs", "W = mv²", "W = IR", "W = mcΔT"],
         "jawaban": "W = Fs",
         "penjelasan": "Usaha terjadi jika gaya menyebabkan perpindahan."}
    ]
}

# =========================
# SESSION STATE
# =========================
if "login" not in st.session_state:
    st.session_state.login = False
if "username" not in st.session_state:
    st.session_state.username = ""
if "index" not in st.session_state:
    st.session_state.index = 0
if "score" not in st.session_state:
    st.session_state.score = 0
if "start" not in st.session_state:
    st.session_state.start = datetime.now()
if "selesai" not in st.session_state:
    st.session_state.selesai = False

# =========================
# LOGIN
# =========================
if not st.session_state.login:
    st.sidebar.header("🔑 Login")
    username = st.sidebar.text_input("Username")
    password = st.sidebar.text_input("Password", type="password")
    login_btn = st.sidebar.button("Login")

    if login_btn:
        if username in users and password == users[username]:
            st.session_state.login = True
            st.session_state.username = username
            st.success(f"Selamat datang, {username}!")
        else:
            st.error("Username atau password salah")
else:
    st.sidebar.write(f"👤 Logged in as: **{st.session_state.username}**")
    logout_btn = st.sidebar.button("Logout")
    if logout_btn:
        st.session_state.login = False
        st.session_state.username = ""
        st.session_state.index = 0
        st.session_state.score = 0
        st.session_state.start = datetime.now()
        st.experimental_rerun()

# =========================
# MENU UTAMA
# =========================
if st.session_state.login:
    menu_options = ["Materi", "Quiz"]
    if st.session_state.username == "admin":
        menu_options.append("Admin/Guru")

    menu = st.sidebar.selectbox("📚 Menu", menu_options)

    # =========================
    # MENU MATERI
    # =========================
    if menu == "Materi":
        pilihan = st.selectbox("Pilih Materi", list(materi.keys()))
        st.header(pilihan)
        st.subheader("📐 Rumus")
        for r in materi[pilihan]["rumus"]:
            st.latex(r)
        st.subheader("📘 Penjelasan")
        st.write(materi[pilihan]["penjelasan"])

    # =========================
    # MENU QUIZ
    # =========================
    elif menu == "Quiz":
        st.header("🎯 Quiz Fisika Edukatif")

        quiz = []
        for soal_list in bank_soal.values():
            quiz.extend(soal_list)

        if st.session_state.index >= len(quiz):
            st.success(f"🎉 Quiz selesai! Skor kamu: {st.session_state.score}")
            st.session_state.selesai = True
        else:
            q = quiz[st.session_state.index]

            batas_waktu = 30
            elapsed = (datetime.now() - st.session_state.start).seconds
            sisa = batas_waktu - elapsed
            if sisa <= 0:
                st.warning("⏱️ Waktu habis! Pindah ke soal berikutnya.")
                st.session_state.index += 1
                st.session_state.start = datetime.now()
                st.experimental_rerun()
            else:
                st.info(f"⏱️ Sisa waktu: {sisa} detik")

            st.subheader(f"Soal {st.session_state.index + 1}")
            st.write(q["soal"])

            jawaban = st.radio("Pilih jawaban:", q["opsi"], key=st.session_state.index)

            jawab_btn = st.button("Jawab")
            next_btn = st.button("Next ➡️")

            if jawab_btn:
                if jawaban == q["jawaban"]:
                    st.success("✅ Jawaban benar!")
                    st.session_state.score += 10
                else:
                    st.error("❌ Jawaban salah")
                    st.write(f"✔ Jawaban benar: **{q['jawaban']}**")
                    st.write(f"📘 Penjelasan: {q['penjelasan']}")

            if next_btn:
                st.session_state.index += 1
                st.session_state.start = datetime.now()
                st.experimental_rerun()

    # =========================
    # MENU ADMIN
    # =========================
    elif menu == "Admin/Guru":
        st.header("👨‍🏫 Menu Admin")
        st.write("Admin dapat memantau hasil quiz siswa:")
        st.metric("Skor Terakhir", st.session_state.score)

st.caption("by Dirma")